[app_settings]
app_version = "0.1.0"
app_name = "Admin"
app_host = "0.0.0.0"
app_port = 8000

[http_client_settings]
products_service_url = "http://products:8000/api/v1/products/"
orders_service_url = "http://orders:8000/api/v1/orders/"
http_timeout = 30.0
http_max_retries = 3

[db_settings]
db_name = "postgres"
db_user = "user"
db_password = "password"
db_host = "admin_db"
db_port = 5432
db_ext_port = 5434

[auth_settings]
secret_key = "web-dev"
algorithm = "HS256"
access_token_expire_minutes = 30
